name: Close issues
on:
    issues:
        types: [labeled]

jobs:
  close-airtable:
    runs-on: ubuntu-latest
    steps:
    - name: close-airtable
      uses: bdougie/close-issues-based-on-label@master
      env:
        LABEL: "closed in airtable"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
